Cosmetic edits.

diff --git a/.github/workflows/ci-validation.yml b/.github/workflows/ci-validation.yml
--- a/.github/workflows/ci-validation.yml
+++ b/.github/workflows/ci-validation.yml
@@ -20,6 +20,7 @@ jobs:
       CTEST_PARALLEL_LEVEL: 4
       IMAGE_TYPE: test
       VALIDATION: ON
+      BUILD_SUCCESS: true
     runs-on: ubuntu-20.04
     steps:
     - uses: actions/checkout@v3
@@ -34,8 +35,15 @@ jobs:
 
     - name: Build (Ubuntu 20.04)
       run: |
-        tools/ci-build.sh
+        tools/ci-build.sh || echo "BUILD_SUCCESS=false" >> $GITHUB_ENV
 
     - name: Validate
-      run: ctest -R toz3-validate-p4c --output-on-failure --schedule-random
+      if: env.BUILD_SUCCESS == 'true'
+      run: |
+          ctest  -R toz3-validate-p4c --output-on-failure --schedule-random
       working-directory: ./build
+
+    - name: Build Failed
+      if: env.BUILD_SUCCESS == 'false'
+      run: |
+          echo "Building Gauntlet failed."
